#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-htrace
Version  : 3.0.4
Release  : 1
URL      : https://repo1.maven.org/maven2/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.jar
Source0  : https://repo1.maven.org/maven2/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.jar
Source1  : https://repo1.maven.org/maven2/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-htrace-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-htrace package.
Group: Data

%description data
data components for the mvn-htrace package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/htrace/htrace-core/3.0.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/htrace/htrace-core/3.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/htrace/htrace-core/3.0.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/htrace/htrace-core/3.0.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.jar
/usr/share/java/.m2/repository/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.pom
